---
- name: add saltstack gpg key
  apt_key: url=https://repo.saltstack.com/apt/ubuntu/{{ ansible_distribution_version }}/amd64/latest/SALTSTACK-GPG-KEY.pub state=present

- name: add saltstack repository
  apt_repository: repo='deb http://repo.saltstack.com/apt/ubuntu/{{ ansible_distribution_version }}/amd64/latest {{ ansible_distribution_release }} main' state=present

- name: update repository
  apt: update_cache=yes 
